// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLLMPrompt() {
  return window['go']['main']['App']['GetLLMPrompt']();
}

export function SaveSVG(arg1, arg2) {
  return window['go']['main']['App']['SaveSVG'](arg1, arg2);
}
